---
title: "Welp...Here is the story"
---
Born and raised in New York City, I have a true passion for baseball. For such an extroverted and fun guy, I say the slow-paced, anaerobic nature of the sport is what excites me most. I am a die-hard Yankees fan who had the pleasure (and I use that term sarcastically) of watching the infamous Game 5, 5th Inning—the game the Yankees lost the 2024 World Series—in person.

Despite being a Yankees fan, I have professional experience with the crosstown rivals, the New York Mets. Some would say I had every NYC dad's dream job: running a memorabilia business where he spent three years collecting game-used and autographed merchandise from the Mets. Through this job, I can confidently say I established relationships with some pretty cool athletes and have attended more than 500 baseball games in my lifetime.

Along with baseball, I am a big fan of college basketball, marathon running (I've completed two in the last eight months), and investing. I'm a St. John's University alumnus and a season ticket holder for their basketball team. I currently pursue a degree in Data Science from Baruch, with the goal of working in player evaluation within the next three to five years.

I consider myself a pretty under-the-radar guy, even though I post a niche Instagram story once-in-a-while updating my loyal followers—my mom, sisters, and grandma. Feel free to join this fan base if you're interested - @samkatzap, or connect with me on LinkedIn - https://www.linkedin.com/in/samuel-katzap/.